// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIWuNfjLBy_m5Hw0DWrxpmt3yex7fj7dA',
    appId: '1:271836857839:web:3e0323e9d3071c279ca21a',
    messagingSenderId: '271836857839',
    projectId: 'curso-frontend-issd-nmar-6500c',
    authDomain: 'curso-frontend-issd-nmar-6500c.firebaseapp.com',
    storageBucket: 'curso-frontend-issd-nmar-6500c.firebasestorage.app',
    measurementId: 'G-LD6N6TF3NM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu7PjGJeUyYvYL0xcUfAIPCEJEWBct_es',
    appId: '1:271836857839:android:101a51c6a1ca98a79ca21a',
    messagingSenderId: '271836857839',
    projectId: 'curso-frontend-issd-nmar-6500c',
    storageBucket: 'curso-frontend-issd-nmar-6500c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDaxE3MGEVraRbD41WjOf5i3SKXn91h7M',
    appId: '1:271836857839:ios:411d5ec6a6952c519ca21a',
    messagingSenderId: '271836857839',
    projectId: 'curso-frontend-issd-nmar-6500c',
    storageBucket: 'curso-frontend-issd-nmar-6500c.firebasestorage.app',
    iosBundleId: 'com.example.burguerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDaxE3MGEVraRbD41WjOf5i3SKXn91h7M',
    appId: '1:271836857839:ios:411d5ec6a6952c519ca21a',
    messagingSenderId: '271836857839',
    projectId: 'curso-frontend-issd-nmar-6500c',
    storageBucket: 'curso-frontend-issd-nmar-6500c.firebasestorage.app',
    iosBundleId: 'com.example.burguerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIWuNfjLBy_m5Hw0DWrxpmt3yex7fj7dA',
    appId: '1:271836857839:web:13a86bdd97b098559ca21a',
    messagingSenderId: '271836857839',
    projectId: 'curso-frontend-issd-nmar-6500c',
    authDomain: 'curso-frontend-issd-nmar-6500c.firebaseapp.com',
    storageBucket: 'curso-frontend-issd-nmar-6500c.firebasestorage.app',
    measurementId: 'G-2F8SNT4CZD',
  );
}
